import { Quote } from './types';

export const APP_NAME = "ښکلې ویناوې";
export const DEVELOPER_NAME = "طالب العلم محمد طیب شجاع";

export const QUOTES_DATA: Quote[] = [
  // Islamic
  { id: 'i1', text: 'صبر د ايمان رڼا ده.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i2', text: 'غوره سړی هغه دی چې نورو ته یې خیر ورسېږي.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i3', text: 'عمل بې له نیته قبول نه دی.', author: 'اسلامي حکمت', category: 'Islamic' },
  { id: 'i4', text: 'د مور دعا د جنت کلي ده.', author: 'نبوي قول', category: 'Islamic' },
  { id: 'i5', text: 'پوهه د مومن ورکه متاع ده.', author: 'حضرت علي (ک)', category: 'Islamic' },
  { id: 'i6', text: 'چا چې پر ځان رحم ونه کړ، پر هغه به رحم ونه شي.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i7', text: 'رښتیا ویل انسان ته نجات ورکوي.', author: 'اسلامي حکمت', category: 'Islamic' },
  { id: 'i8', text: 'کبر او غرور د انسان د تباهۍ لامل دی.', author: 'حضرت علي (ک)', category: 'Islamic' },
  { id: 'i9', text: 'چې د بل چا عیبونه پټوي، خدای به د هغه عیبونه پټ کړي.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i10', text: 'مظلوم ته د ظالم له شره پناه ورکول تر ټولو غوره عبادت دی.', author: 'دیني وینا', category: 'Islamic' },
  { id: 'i11', text: 'الله پاک له هغه چا سره دی چې صبر کوي.', author: 'قرآني مفهوم', category: 'Islamic' },
  { id: 'i12', text: 'روژه د دوزخ له اوره ډال ده.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i13', text: 'ورورولي او مینه د ایمان برخه ده.', author: 'اسلامي لارښود', category: 'Islamic' },
  { id: 'i14', text: 'د مور او پلار رضا د خدای رضا ده.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i15', text: 'علم زده کول په هر مسلمان نارینه او ښځه فرض دی.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i16', text: 'الله (ج) ښکلا خوښوي، نو پاکي غوره کړئ.', author: 'نبوي قول', category: 'Islamic' },
  { id: 'i17', text: 'د یتیم او مسکین پالنه د جنت دروازې خلاصوي.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i18', text: 'شکر ویستل مو نعمتونه زیاتوي.', author: 'قرآني مفهوم', category: 'Islamic' },
  { id: 'i19', text: 'لمونځ د دین ستنه ده.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i20', text: 'په غوسه کې تصمیم مه نیسه او په خوشحالۍ کې وعده مه کوه.', author: 'حضرت علي (ک)', category: 'Islamic' },
  { id: 'i21', text: 'حیا د ایمان یوه برخه ده.', author: 'نبوي لارښوونه', category: 'Islamic' },
  { id: 'i22', text: 'د مومن زړه د خدای (ج) کور دی.', author: 'صوفي قول', category: 'Islamic' },
  { id: 'i23', text: 'د حق ویلو لپاره تل پیاوړی اوسه.', author: 'اسلامي حکمت', category: 'Islamic' },
  { id: 'i24', text: 'که څوک له لارې اغزي لرې کړي، صدقه ده.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i25', text: 'د دنیا ژوند یوازې لنډه ازموینه ده.', author: 'قرآني مفهوم', category: 'Islamic' },
  { id: 'i26', text: 'زکات مال پاکوي او وده ورکوي.', author: 'اسلامي تعلیمات', category: 'Islamic' },
  { id: 'i27', text: 'د ګاونډي حقوق پر هر مسلمان فرض دي.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i28', text: 'کله چې عقل بشپړ شي، نو خبرې کمې شي.', author: 'حضرت علي (ک)', category: 'Islamic' },
  { id: 'i29', text: 'صدقه بلاوې دفع کوي.', author: 'نبوي حدیث', category: 'Islamic' },
  { id: 'i30', text: 'مړه زړونه د خدای په ذکر ژوندي کېږي.', author: 'قرآني لارښوونه', category: 'Islamic' },
  { id: 'i31', text: 'غوره جهاد د خپل نفس په وړاندې مبارزه ده.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i32', text: 'د مؤمن لپاره هر کار کې خیر وي.', author: 'نبوي قول', category: 'Islamic' },
  { id: 'i33', text: 'نیت چې پاک وي، منزل به نږدې وي.', author: 'اسلامي حکمت', category: 'Islamic' },
  { id: 'i34', text: 'د الله په ورکړه قناعت کوونکی تل شتمن وي.', author: 'دیني لارښود', category: 'Islamic' },
  { id: 'i35', text: 'د پوهې غوښتنه له زانګو تر ګوره وکړه.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'i36', text: 'هغوی چې پر خدای توکل کوي، هیڅکله نه ناهیلي کېږي.', author: 'قرآني مفهوم', category: 'Islamic' },
  { id: 'i37', text: 'د بل په بد ویلو کې خپل ایمان مه ضایع کوه.', author: 'نبوي قول', category: 'Islamic' },

  // Philosophers
  { id: 'p1', text: 'خپل ځان وپېژنه.', author: 'سقراط', category: 'Philosophers' },
  { id: 'p2', text: 'زده کړه یوازې د کتاب لوستل نه، بلکې د ذهن روزنه ده.', author: 'برټرانډ رسل', category: 'Philosophers' },
  { id: 'p3', text: 'ژوند هله ارزښت لري چې هدف ولري.', author: 'ارستو', category: 'Philosophers' },
  { id: 'p4', text: 'هغه څوک چې فکر نه کوي، هغه ازاد نه دی.', author: 'افلاطون', category: 'Philosophers' },
  { id: 'p5', text: 'ما غوښتل نړۍ بدله کړم، خو پوه شوم چې باید لومړی ځان بدل کړم.', author: 'رومي', category: 'Philosophers' },
  { id: 'p6', text: 'شکار هغه وخت بریالی دی، چې ښکارکوونکی په خپل ځان کنټرول ولري.', author: 'نیچه', category: 'Philosophers' },
  { id: 'p7', text: 'پوهه هغه ځواک دی چې تر ټولو اغېزمنه وسله ده.', author: 'فرانسس بیکن', category: 'Philosophers' },
  { id: 'p8', text: 'لویه تېروتنه دا ده چې د خپل ژوند د ستونزو لپاره بل څوک پړ وګڼې.', author: 'ژان پل سارتر', category: 'Philosophers' },
  { id: 'p9', text: 'فکر کوم، نو ځکه شتون لرم.', author: 'رنه دیکارت', category: 'Philosophers' },
  { id: 'p10', text: 'وخت هر زخم رغوي.', author: 'لرغونی حکمت', category: 'Philosophers' },
  { id: 'p11', text: 'د پوهې پیل پوښتنه ده.', author: 'سقراط', category: 'Philosophers' },
  { id: 'p12', text: 'یوازینی رښتینی حکمت په دې پوهېدلو کې دی چې ته هیڅ نه پوهېږې.', author: 'سقراط', category: 'Philosophers' },
  { id: 'p13', text: 'بدلون د ژوند یوازینی دوامدار حقیقت دی.', author: 'هیراکلیتوس', category: 'Philosophers' },
  { id: 'p14', text: 'د غوسې پای پښېماني ده.', author: 'سیډارتا ګوتما', category: 'Philosophers' },
  { id: 'p15', text: 'هغه ملت چې خپل تاریخ هېر کړي، مجبور دی بیا یې تکرار کړي.', author: 'سانتایانا', category: 'Philosophers' },
  { id: 'p16', text: 'انساني ذهن یو خالي کاغذ دی چې تجربې ورباندې لیکل کېږي.', author: 'جان لاک', category: 'Philosophers' },
  { id: 'p17', text: 'ازادي د مسئولیت په معنا ده.', author: 'سارتر', category: 'Philosophers' },
  { id: 'p18', text: 'د بل په خوښۍ کې خپله خوښي لټول لوی هنر دی.', author: 'فیلسوف', category: 'Philosophers' },
  { id: 'p19', text: 'رښتینولي تر ټولو لوړ فضیلت دی.', author: 'کانټ', category: 'Philosophers' },
  { id: 'p20', text: 'انسان طبعاً ټولنیز دی.', author: 'ارستو', category: 'Philosophers' },
  { id: 'p21', text: 'د هوښیار عقل د هغه په زړه کې وي، او د ناپوه زړه د هغه په خوله کې.', author: 'حضرت علي (ک)', category: 'Philosophers' },

  // Success
  { id: 's1', text: 'بریا د هڅو او صبر نتیجه ده.', author: 'پښتو ادب', category: 'Success' },
  { id: 's2', text: 'کله چې تسلیم نه شې، ماته نه خورې.', author: 'مشهوره وینا', category: 'Success' },
  { id: 's3', text: 'وخت د بریا تر ټولو لویه شتمني ده.', author: 'شجاع', category: 'Success' },
  { id: 's4', text: 'د خپلو خوبونو د رښتیا کولو لپاره نن ګام پورته کړه.', author: 'هڅونکې وینا', category: 'Success' },
  { id: 's5', text: 'ناکامي د بریا د پیل لومړی ګام دی.', author: 'توماس اډیسن', category: 'Success' },
  { id: 's6', text: 'که غواړې بریالی شې نو له ستونزو مه تښته.', author: 'سقراط', category: 'Success' },
  { id: 's7', text: 'یوازې هغه خلک بریالي کېږي، چې پخپله یې هڅه کړې وي.', author: 'البرټ انشټاین', category: 'Success' },
  { id: 's8', text: 'بریا تر ټولو خوږ انتقام دی.', author: 'وینا', category: 'Success' },
  { id: 's9', text: 'خپل ذهن تل په مثبتو افکارو بوخت ساته.', author: 'رواني لارښود', category: 'Success' },
  { id: 's10', text: 'هغه څه چې موږ نه وژني، لا مو پسې پیاوړي کوي.', author: 'نیچه', category: 'Success' },
  { id: 's11', text: 'نننۍ هڅه سبانۍ بریا ده.', author: 'هڅونکی', category: 'Success' },
  { id: 's12', text: 'هیله هغه مشعل دی چې د بریا لاره روښانوي.', author: 'حکمت', category: 'Success' },
  { id: 's13', text: 'هر اوږد سفر په یوه کوچني ګام پیل کېږي.', author: 'لاو تزو', category: 'Success' },
  { id: 's14', text: 'فرصتونه نه رامنځته کېږي، بلکې جوړېږي.', author: 'وینا', category: 'Success' },
  { id: 's15', text: 'مثبت فکر کول نیمه بریا ده.', author: 'وینا', category: 'Success' },
  { id: 's16', text: 'خپل هدف ته د رسېدو لپاره تمرکز خورا اړین دی.', author: 'کارپوه', category: 'Success' },
  { id: 's17', text: 'په ځان باور د بریالیتوب لومړی راز دی.', author: 'رالف والډو', category: 'Success' },
  { id: 's18', text: 'وخت هیڅکله د هیچا لپاره نه درېږي.', author: 'وینا', category: 'Success' },
  { id: 's19', text: 'هڅه وکړه چې یو ارزښتمن انسان اوسې، نه یوازې بریالی.', author: 'انشټاین', category: 'Success' },
  { id: 's20', text: 'تېروتنې مو لوی ښوونکي دي.', author: 'تجربه', category: 'Success' },
  { id: 's21', text: 'کله چې نور خوب کوي، ته کار کوه.', author: 'وینا', category: 'Success' },
  { id: 's22', text: 'که غواړې لوی کارونه وکړې، له کوچنیو پیل کړه.', author: 'حکیم', category: 'Success' },
  { id: 's23', text: 'بریا ستا په اراده پورې اړه لري.', author: 'ارواپوه', category: 'Success' },

  // Life Advice
  { id: 'l1', text: 'پر هر چا باور مه کوه، خو له هر چا سره نېکي کوه.', author: 'پښتو متل', category: 'Life Advice' },
  { id: 'l2', text: 'ژوند لنډ دی، په کینه او نفرت کې یې مه ضایع کوئ.', author: 'حکمت', category: 'Life Advice' },
  { id: 'l3', text: 'د پوه سړي ملګرتیا ستا ژوند بدلولی شي.', author: 'ملي استازي', category: 'Life Advice' },
  { id: 'l4', text: 'هیڅکله مه تسلیمېږه، ځکه لوی کارونه وخت نیسي.', author: 'وینا', category: 'Life Advice' },
  { id: 'l5', text: 'خpله کمزورتیا په خپل ځواک بدله کړه.', author: 'تجربه طلب', category: 'Life Advice' },
  { id: 'l6', text: 'تل رښتیا وایه که څه هم ترخه وي.', author: 'پښتو وینا', category: 'Life Advice' },
  { id: 'l7', text: 'غصه هغه زهر دي چې انسان یې په خپله څښي.', author: 'حکیم', category: 'Life Advice' },
  { id: 'l8', text: 'غیبت کول د انسان شخصیت او اعتبار له منځه وړي.', author: 'حکمت', category: 'Life Advice' },
  { id: 'l9', text: 'چې څه کرې، هغه به رېبې.', author: 'پښتو متل', category: 'Life Advice' },
  { id: 'l10', text: 'مهرباني یوه ژبه ده چې ړانده یې هم لیدلای شي او کاڼه یې اورېدلو سره احساسولی شي.', author: 'مارک ټوین', category: 'Life Advice' },
  { id: 'l11', text: 'صحت تر ټولو لویه شتمني ده.', author: 'حکمت', category: 'Life Advice' },
  { id: 'l12', text: 'عقلمند انسان په اورېدلو سره ډېر څه زده کوي.', author: 'تجربه', category: 'Life Advice' },
  { id: 'l13', text: 'د نن کار سبا ته مه پرېږده.', author: 'پښتو متل', category: 'Life Advice' },
  { id: 'l14', text: 'بد ګومانول له بدو عملونو هم ناوړه دی.', author: 'مشران', category: 'Life Advice' },
  { id: 'l15', text: 'احترام کوه چې احترام دې وشي.', author: 'وینا', category: 'Life Advice' },
  { id: 'l16', text: 'که غواړې چې آرامه ژوند ولرې، له تمې تېر شه.', author: 'پښتو متل', category: 'Life Advice' },
  { id: 'l17', text: 'خپل راز چا ته مه وایه، که یې پخپله نه شې ساتلی.', author: 'حکیم', category: 'Life Advice' },

  // Poets
  { id: 'po1', text: 'که په میوند کې شهید نه شوې، ګرانه لالیه بې ننګۍ ته دې ساتینه.', author: 'ملالۍ میوندۍ', category: 'Poets' },
  { id: 'po2', text: 'زه پښتون یم، زما مینه له پښتو ده.', author: 'خوشحال خان خټک', category: 'Poets' },
  { id: 'po3', text: 'وطن مو د غاړې هار دی.', author: 'رحمان بابا', category: 'Poets' },
  { id: 'po4', text: 'اور مې پر ځان پورې کړ، ستا له غمه نه ژاړم.', author: 'حمزه بابا', category: 'Poets' },
  { id: 'po5', text: 'د دنیا ژوند یو خواب دی، چې سړی ترې ژر پاڅېږي.', author: 'رحمان بابا', category: 'Poets' },
  { id: 'po6', text: 'د مینې په لار کې هر خار هم یو ګل دی.', author: 'پښتو شعر', category: 'Poets' },
  { id: 'po7', text: 'چې یار مې نشته، دا دنیا مې څه په کار ده؟', author: 'غني خان', category: 'Poets' },
  { id: 'po8', text: 'زه د عشق په درس کې یوازې ستا نوم وایم.', author: 'کلاسیک شعر', category: 'Poets' },
  { id: 'po9', text: 'که مې سر په دار وخېژي، بیا به هم وایم چې پښتون یم.', author: 'ملي شاعر', category: 'Poets' },
  { id: 'po10', text: 'ستاسو د سترګو جادو مې زړه یووړ.', author: 'حبیب الله', category: 'Poets' },
  { id: 'po11', text: 'ما ته د ګلونو په څېر نرم اوسه.', author: 'پښتو ادب', category: 'Poets' },
  { id: 'po12', text: 'په دې نړۍ کې هیڅ شی هم د تل لپاره نه دي.', author: 'صوفي شاعر', category: 'Poets' },
  { id: 'po13', text: 'لکه شمع یم، د نورو لپاره سوځم.', author: 'درویش دراني', category: 'Poets' },
  { id: 'po14', text: 'د خپل ځان په لټه کې مې ټوله نړۍ ولټوله.', author: 'رومي', category: 'Poets' },
  { id: 'po15', text: 'د مینې په بازار کې زړه یوازینۍ سکه ده.', author: 'شاعر', category: 'Poets' },
  { id: 'po16', text: 'د وطن مینه له ایمان څخه ده.', author: 'شاعر', category: 'Poets' },

  // Knowledge
  { id: 'k1', text: 'پوهه هغه وسله ده چې نړۍ پرې بدلولای شو.', author: 'نیلسن منډیلا', category: 'Knowledge' },
  { id: 'k2', text: 'د مطالعې پټه نړۍ ته دروازه کتاب دی.', author: 'لیکوال', category: 'Knowledge' },
  { id: 'k3', text: 'بې علمه سړی د ړانده په څېر دی.', author: 'پښتو وینا', category: 'Knowledge' },
  { id: 'k4', text: 'کتاب تر ټولو ښه ملګری دی چې هیڅکله خیانت نه کوي.', author: 'حکمت', category: 'Knowledge' },
  { id: 'k5', text: 'هوښیار هغه دی چې تل زده کړه کوي.', author: 'حکیم', category: 'Knowledge' },
  { id: 'k6', text: 'توره تیاړه په پوهې رڼا کولی شو.', author: 'پوهان', category: 'Knowledge' },
  { id: 'k7', text: 'قلم تر تورې ډېر ځواکمن دی.', author: 'متل', category: 'Knowledge' },
  { id: 'k8', text: 'د جهالت ناروغي تر بل هر درد سخته ده.', author: 'پښتو وینا', category: 'Knowledge' },
  { id: 'k9', text: 'د کتاب لوستل د زرګونو کلونو سفر دی.', author: 'لیکوال', category: 'Knowledge' },
  { id: 'k10', text: 'څوک چې مطالعه پرېږدي، د هغه ذهن وچېږي.', author: 'حکمت', category: 'Knowledge' },
  { id: 'k11', text: 'د زده کړې ریښې ترخې دي خو مېوه یې خوږه ده.', author: 'ارستو', category: 'Knowledge' },
  { id: 'k12', text: 'پوهه دوه ډوله ده: یا په یوه شي پوهېږو، یا پوهېږو چې د حل لاره یې چېرته پیدا کړو.', author: 'سامویل', category: 'Knowledge' },
  { id: 'k13', text: 'ښوونکی د ټولنې معمار دی.', author: 'پوهان', category: 'Knowledge' },
  { id: 'k14', text: 'علم یو بې پایه سمندر دی.', author: 'لیکوال', category: 'Knowledge' },

  // Patience
  { id: 'pa1', text: 'صبر تریخ دی خو مېوه یې خوږه ده.', author: 'متل', category: 'Patience' },
  { id: 'pa2', text: 'د سختو شپو پای روښانه سهار وي.', author: 'هڅونکی', category: 'Patience' },
  { id: 'pa3', text: 'صبر د هرې ستونزې کلیدي ده.', author: 'حکمت', category: 'Patience' },
  { id: 'pa4', text: 'له عجلې څخه شیطان خوشحالېږي.', author: 'اسلامي وینا', category: 'Patience' },
  { id: 'pa5', text: 'هغوی چې صبر لري، هر څه ترلاسه کولی شي.', author: 'تجربه', category: 'Patience' },
  { id: 'pa6', text: 'آرامي د لویو پرېکړو لپاره اړینه ده.', author: 'مشران', category: 'Patience' },
  { id: 'pa7', text: 'هره تیاره شپه یوه روښانه ورځ لري.', author: 'حکیمه وینا', category: 'Patience' },
  { id: 'pa8', text: 'خپل درد وزغمه، خو بې همته کېږه مه.', author: 'متل', category: 'Patience' },
  { id: 'pa9', text: 'چې په صبر کار اخلي، خدای ورسره دی.', author: 'دیني لارښوونه', category: 'Patience' },
  { id: 'pa10', text: 'تل آرام اوسه، حتی کله چې طوفان وي.', author: 'طبیعت', category: 'Patience' },
  { id: 'pa11', text: 'صبر د بریالیتوب تر ټولو نږدې لاره ده.', author: 'وینا', category: 'Patience' },

  // Leaders
  { id: 'lea1', text: 'خدمت د مشرۍ لومړی شرط دی.', author: 'باچا خان', category: 'Leaders' },
  { id: 'lea2', text: 'آزادي اخیستل کېږي، ورکول کېږي نه.', author: 'ملي مشر', category: 'Leaders' },
  { id: 'lea3', text: 'بې غیرته ژوند، له مرګه هم بدتر دی.', author: 'احمد شاه بابا', category: 'Leaders' },
  { id: 'lea4', text: 'رښتینی مشر هغه دی چې د ملت لپاره قرباني ورکړي.', author: 'میرویس نیکه', category: 'Leaders' },
  { id: 'lea5', text: 'یووالی مو ځواک دی، بېلتون مو مرګ.', author: 'سیاسي لارښود', category: 'Leaders' },
  { id: 'lea6', text: 'سیاست د اخلاقو پرته هیڅ نه دی.', author: 'مشران', category: 'Leaders' },
  { id: 'lea7', text: 'بامسؤلیته خلک تل ټولنې ته ګټه رسوي.', author: 'وینا', category: 'Leaders' },
  { id: 'lea8', text: 'هغه مشر چې د خپلو خلکو غږ نه اوري، ماتې خوري.', author: 'تاریخ', category: 'Leaders' },
  { id: 'lea9', text: 'قوي رهبري په نرمۍ او قاطعیت کې ده.', author: 'سیاستوال', category: 'Leaders' },
  { id: 'lea10', text: 'ملت د یوې کورنۍ په څېر دی، باید سالم وساتل شي.', author: 'ولسمشر', category: 'Leaders' },
  { id: 'lea11', text: 'د ملت خدمت تر هر څه لوړ دی.', author: 'مشر', category: 'Leaders' },

  // Happiness
  { id: 'h1', text: 'خوښي په مال کې نه بلکې په قناعت کې ده.', author: 'حکیمه وینا', category: 'Happiness' },
  { id: 'h2', text: 'مسکا د زړونو تر ټولو لنډه لاره ده.', author: 'انساني وینا', category: 'Happiness' },
  { id: 'h3', text: 'که غواړې خوشاله اوسې، نو له هغو څیزونو خوند واخله چې لرې یې.', author: 'حکمت', category: 'Happiness' },
  { id: 'h4', text: 'خوښي یو انتخاب دی، نه هدف.', author: 'رواني ډاکټر', category: 'Happiness' },
  { id: 'h5', text: 'د نورو له خوشالۍ سره خوشالي کول لویه نېکي ده.', author: 'وینا', category: 'Happiness' },
  { id: 'h6', text: 'خوښي د مننې له زړه څخه راپیدا کېږي.', author: 'تجربه', category: 'Happiness' },
  { id: 'h7', text: 'څومره چې ساده ژوند کوې، هغومره خوشحاله یې.', author: 'حکیم', category: 'Happiness' },
  { id: 'h8', text: 'مینه هغه ځواک دی چې نړۍ پرې خوشحاله ده.', author: 'شاعر', category: 'Happiness' },
  { id: 'h9', text: 'هیڅکله مه هېروه چې خاندې.', author: 'مثبت روان', category: 'Happiness' },
  { id: 'h10', text: 'د نن ورځې ارزښت وپېژنه ترڅو خوشحاله یې.', author: 'وینا', category: 'Happiness' },
  { id: 'h11', text: 'خپله خوشالي په نورو کې ولټوه.', author: 'حکمت', category: 'Happiness' },
  
  // Love (Added newly based on Categories list having Love)
  { id: 'lo1', text: 'مینه هغه جذبه ده چې زړه ته ژوند ورکوي.', author: 'پښتو شعر', category: 'Love' },
  { id: 'lo2', text: 'بې مینې ژوند لکه بې اوبو سیند.', author: 'متل', category: 'Love' },
  { id: 'lo3', text: 'رښتینې مینه هیڅکله نه زړېږي.', author: 'عاشق', category: 'Love' },
  { id: 'lo4', text: 'د زړه په ژبه خبرې کول یوازې مینه وال کولی شي.', author: 'شاعر', category: 'Love' },
  { id: 'lo5', text: 'مینه هغه اور دی چې رڼا ورکوي خو نه سوځي.', author: 'صوفي', category: 'Love' },
  { id: 'lo6', text: 'ستوري په آسمان کې او ته زما په زړه کې یې.', author: 'پښتو شعر', category: 'Love' },
  { id: 'i38', text: 'زړه چې پاک وي، د خدای رڼا پکې څرګندېږي.', author: 'صوفي قول', category: 'Islamic' },
  { id: 'i39', text: 'د علم خزانه په پوښتنه کولو سره خلاصېږي.', author: 'دیني لارښوونه', category: 'Islamic' },
  { id: 'i40', text: 'مؤمن د بل مؤمن لپاره لکه هنداره وي.', author: 'نبوي ارشاد', category: 'Islamic' },
  { id: 'p22', text: 'خپلواکي په دې کې نه ده چې هر څه وکړې، بلکې په دې کې ده چې د هر کار د نه کولو واک ولرې.', author: 'ژان ژاک روسو', category: 'Philosophers' },
  { id: 'p23', text: 'ژوند یو سفر دی، نه یو منزل.', author: 'امرسن', category: 'Philosophers' },
  { id: 's24', text: 'بریالی هغه څوک دی چې له تېروتنو يې پند اخیستی وي.', author: 'هنري فورډ', category: 'Success' },
  { id: 's25', text: 'که غواړې بریا ته ورسېږې، تل له تېروتنو زده کړه وکړه.', author: 'حکمت', category: 'Success' },
  { id: 'l18', text: 'مشرانو ته درناوی، د ځان درناوی دی.', author: 'پښتو متل', category: 'Life Advice' },
  { id: 'l19', text: 'هغه دوست چې په سخته کې پکار نشي، دوست نه دی.', author: 'متل', category: 'Life Advice' },
  { id: 'po17', text: 'د وطن د عشق په اور کې مې هډوکي ایره شول.', author: 'شاعر', category: 'Poets' },
  { id: 'po18', text: 'هر ښکلی رنګ د بل چا د زړه داغ دی.', author: 'غني خان', category: 'Poets' },
  { id: 'k15', text: 'زده کړه یوازې پوهه نه ده، بلکې د ښه ژوند کولو چل دی.', author: 'پوهان', category: 'Knowledge' },
  { id: 'pa12', text: 'صبر هغه څراغ دی چې په تیاره کې لاره ښيي.', author: 'حکمت', category: 'Patience' },
  { id: 'lea12', text: 'مشر توب د قدرت ښودل نه، بلکې د مسئولیت منل دي.', author: 'حکمت', category: 'Leaders' },
  { id: 'h12', text: 'خوښي هغه عطر دي چې پر نورو یې وشیندې، پخپله هم بې برخې نه پاتې کېږې.', author: 'وینا', category: 'Happiness' }
];

export const CATEGORIES = [
  { id: 'Islamic', name: 'اسلامي ویناوې', icon: 'moon-star' },
  { id: 'Philosophers', name: 'د فیلسوفانو ویناوې', icon: 'brain' },
  { id: 'Success', name: 'د بریا رازونه', icon: 'trending-up' },
  { id: 'Life Advice', name: 'د ژوند لارښوونې', icon: 'compass' },
  { id: 'Love', name: 'د مینې ویناوې', icon: 'heart' },
  { id: 'Patience', name: 'د صبر فضیلت', icon: 'timer' },
  { id: 'Knowledge', name: 'د علم رڼا', icon: 'book-open' },
  { id: 'Happiness', name: 'د خوښۍ لاره', icon: 'smile' },
  { id: 'Poets', name: 'د شاعرانو وینا', icon: 'pen-tool' },
  { id: 'Leaders', name: 'د مشرانو خبرې', icon: 'users' },
];
